### ISSUE TITLE
APT security is completely bypassed

### ISSUE THREAD

**Issue by DonKult** [joeky888/app-fast#1]
APT assumes files in `/var/cache/apt/archives` to be verified doing only a very limited filesize sanity-check, NOT a security check. So just like in various apt-fast implementations using this app-fast implementation allows an attacker to easily hand out backdoors – but at least the download of the backdoors is "fast".

Users should have a look at the apt-transport-mirror manpage (included in upcoming Debian Buster, but earlier Debian versions have a similar implementation, just not the manpage. Ubuntu of course as well in various versions) for a fully supported way of downloading from multiple mirrors in parallel (rather than bashing a single server as a traffic jam is sheldomly solved by adding more cars).

This implementation might be "fixed" by dropping files into `partial/` at least. Not a good solution, but it should work for the time being. I have not looked at the code handling the other package managers, but I guess they have similar issues (at least as far as those package managers have security features at all).

Disclaimer: I am an APT developer and consider Supercow my close friend. I have not and will not use this or any other of these so called accelerator scripts. This is hence not at all an endorsement and never will be one even if ALL bugs are fixed. This is also not a security review, in fact, I looked just 2 seconds. Got here via reddit and wondered why this script describes itself as "evil" – now I and hopefully you, too, know why.

Supercow wonders why so many people seem to be so fascinated by the Top Gun movie and is re-watching it now on german telvision…

> I feel the need… The need for speed

**Comment by joeky888** [comment]
> allows an attacker to easily hand out backdoors

It just downloads the packages first before executing the original apt command.

How does an attacker setup backdoors?

**Comment by DonKult** [comment]
You aren't just downloading – or well, you are, but that isn't what you implicitly claim to do. You are claiming that the files passed all security checks: APT downloads files to `/var/cache/apt/archives/partial` and after the expensive security verification moves them to `/var/cache/apt/archives`. As your script downloads to that directory directly an attacker can ship a user practically any file (minus that it must have the same filesize as the expected file, but that is trivial to do).

Just because the API here is file-based doesn't mean it is a public and supported API. As any application has with its private APIs and data: There are numerous assumptions and expectations made. Apart from the security thing there are e.g. expectations about the filename as well which you aren't taking into consideration. The script is just pretending that the filename part of the URI will also be the correct filename on disk – which isn't true in all cases (e.g. epochs) as the URI can (and is frequently) freely chosen by the repository while the filename is chosen by apt; that is the case for `partial/` as well which is why I mentioned it as incomplete solution in the first comment.

**Comment by joeky888** [comment]
Looks good to me.
