### ISSUE TITLE
Not work on macOS

### ISSUE THREAD

**Issue by gbanyan** [joeky888/app-fast#2]
My environment was macOS 10.13.4, with homebrew and aria2 already installed. 
I followed your guide to install the app-fast on my machine, tried to execute to install something but returned nothing. 
The expected installed app was not installed
I know the author did not have Mac machine, if test needed, I'd like to help.

**Comment by joeky888** [comment]
A screenshot or some logs would be helpful.

Which package you were trying to install?

**Comment by gbanyan** [comment]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/21143869/52761771-bf354600-304f-11e9-9b71-ad659eba471e.png">

As the image showed, I tried to install iftop package, but app-fast command directly returned with no package installed.

**Comment by joeky888** [comment]
Fixed in 5e7910a69b1216e585f301a4432388631e88d189
