### ISSUE TITLE
Possibility to change the cachedir?

### ISSUE THREAD

**Issue by Nosirus** [joeky888/app-fast#4]
how to change the destination of the pacman cachedir?

does the script necessarily move to /var/cache/pacman/pkg?

I would like to use it for the installation of the system, but I block "pacstrap /mnt base base-devel" because of this

**Comment by joeky888** [comment]
I think this script will work even if you don't have the permission to access `/var/cache/pacman/pkg`

Try

```sh
cd /tmp
app-fast -S base-devel
```

**Comment by joeky888** [comment]
I don't use Archlinux but 434a94f897a92dc67055ead1aae5981afd644957 should fix this.
