### ISSUE TITLE
Download only?

### ISSUE THREAD

**Issue by Nosirus** [joeky888/app-fast#5]
is it possible that it only downloads packages? without launching pacman then to install?

**Comment by joeky888** [comment]
Use case?

**Comment by Nosirus** [comment]
to use it with other script, as in my other issues (pacstrap) which uses pacman but which is very long to combine with your script it will help a lot.

Being able to pre-download and choose the destination folder will do me a great service

(sorry for my english level ^^)

**Comment by joeky888** [comment]
You can fork your own version and remove these lines:

```sh
echo "Executing: pacman $@"
pacman $(echo "$1" | sed "s/y//g") ${@:2} && rm -f app-fast.list && exit 0
exit 1
```

I'll keep my own version :)
