### ISSUE TITLE
-Sy works?

### ISSUE THREAD

**Issue by Nosirus** [joeky888/app-fast#6]
when I use the -Sy function I do not see the list of mirrors get updated

if the function is not in place possible to add it?

**Comment by joeky888** [comment]
Pretty sure it works, I always upgrade my system like this.

```sh
app-fast -Syyu
```

**Comment by Nosirus** [comment]
oh ok, I saw no indication so I ask myself the question :)

**Comment by joeky888** [comment]
:)
